/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.trg.fms.api;
@org.apache.avro.specific.AvroGenerated
public enum HeartbeatType implements org.apache.avro.generic.GenericEnumSymbol<HeartbeatType> {
  TYPE60, TYPE80  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"HeartbeatType\",\"namespace\":\"com.trg.fms.api\",\"symbols\":[\"TYPE60\",\"TYPE80\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
