/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.trg.fms.api;
@org.apache.avro.specific.AvroGenerated
public enum TripState implements org.apache.avro.generic.GenericEnumSymbol<TripState> {
  START, ACTIVE, STOP  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"TripState\",\"namespace\":\"com.trg.fms.api\",\"symbols\":[\"START\",\"ACTIVE\",\"STOP\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
